name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'back-end/**'

jobs: 
  primeiro-job:  
    runs-on: windows-latest
    steps:  
      - run: echo "Primeiro Passo"
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
      - name: Status
        run: echo "Status ${{ job.status }}"
