name: CI Back-end
 
on:
  push:
    branches:
      - 'main'
    paths: 
      - 'back-end/**'

jobs: 
  teste:  
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Teste
        working-directory: back-end/
        run: mvn --activate-profiles prod test 
  create:  
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Create Jar
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
