name: CI Fron-end 

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'front-end**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Teste 
        working-directory: front-end/
        run: npm install
  create:
    needs: test
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node / Angular
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
          distribution: 'zulu'
